spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/vardi
  username: postgres
  password: 12345


server:
  port: 5000
spring:
  sql:
    init:
      platform: postgres
  
      